spring:
  application:
    name: monitorizacion-registro
  kafka:
    bootstrap-servers: 23.23.229.144:29092
    consumer:
      group-id: grupo-monitorizacion
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
            spring.json.trusted.packages: "*"
            spring.json.use.type.headers: false
            spring.json.value.default.type: "cl.duoc.monitorizacion_registro.model.RegistroDTO"
  
  datasource:
    url: jdbc:oracle:thin:@//18.211.29.243:1521/XE
    username: monitor_bus
    password: bus123
    driver-class-name: oracle.jdbc.OracleDriver
  
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: validate 
    show-sql: true